### ISSUE TITLE
i18n keys broken

### ISSUE THREAD

**Issue by Shramkoweb** [StateOfJS/state-of-js-graphql-results-api#109]
![image](https://user-images.githubusercontent.com/42001531/102007909-82166980-3d35-11eb-903d-f53b685bed86.png)

this reproduce in all languages

**Comment by SachaG** [comment]
Can you try again? It can sometimes happen if the API is not loading.

**Comment by Shramkoweb** [comment]
> Can you try again? It can sometimes happen if the API is not loading.

The error remains. And i find new: incorrect active block state
![image](https://user-images.githubusercontent.com/42001531/102010494-09b8a400-3d47-11eb-8601-33b32e815744.png)

**Comment by SachaG** [comment]
I'm also seeing the incorrect nav state but I can't reproduce the missing i18n strings?
