### ISSUE TITLE
Add missing resources and other projects

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/state-of-js-graphql-results-api#4]
<img width="568" alt="Screen Shot 2019-12-21 at 16 21 21" src="https://user-images.githubusercontent.com/358832/71304744-f44bbb00-240d-11ea-879d-b296c5e8b3ba.png">

There are still quite a few resources not properly formatted and/or linked up on:

https://2019.stateofjs.com/resources/

As well as a few other tools on:

https://2019.stateofjs.com/other-tools/

If you'd like to help you can submit a PR to add the missing items to this file:

https://github.com/StateOfJS/state-of-js-graphql-results-api/blob/master/src/data/entities.yml

Following this structure:

```
- id: syntaxfm
  name: Syntax
  homepage: https://syntax.fm/
  description: A great podcast
  category: podcasts
```

Where `id` is the character string used in the chart (some of them are truncated which makes copy/pasting them a bit harder, sorry… You can hover on the bar to see the full string).

`name` will be used as the properly formatted name, and `homepage` will optionally be the URL linked to. `description` and `category` are optional and not currently used but we might use them in the future if we want to build out a more fleshed out directory of JavaScript resources.

Note that once a PR is merged to add in more resources, we still need to manually clear the API cache and rebuild the site before the changes are live, so it won't be instant.  

**Important**: to avoid many people doing overlapping work please post here indicating which block's resources (Other Blogs & Magazines, Podcasts etc.) you want to work on and make sure nobody else is working on that first.

**Comment by michaelrambeau** [comment]
I'm taking care of the missing links about JavaScript projects in https://2019.stateofjs.com/other-tools/ page.
It can be fixed by adding more aliases to the project list coming from [Best of JavaScript](https://bestofjs.org/)

* Pika (`@pika/web`)
* Numeral (`Numeral.js`)
* ...

**Comment by SachaG** [comment]
Looks like me and @michaelrambeau got it covered :)
