### ISSUE TITLE
Can we add this repo to the Hacktoberfest event?

### ISSUE THREAD

**Issue by timbergus** [StateOfJS/state-of-js-graphql-results-api#47]
We only need to add the `hacktoberfest` topic to the repo ([instructions](https://hacktoberfest.digitalocean.com/hacktoberfest-update)). I don't know if it's possible, but it would be cool to participate in the event this year 🙂

**Comment by SachaG** [comment]
I'm a bit worried about spam… I'd rather add the `hacktoberfest-accepted` topic to PRs I think?

**Comment by timbergus** [comment]
Yes, much better. Thanks a lot! I've seen you have already added the label to the latest ones. Would you mind adding it to these two too?

PR1: [https://github.com/StateOfJS/StateOfJS-Vulcan/pull/36](https://github.com/StateOfJS/StateOfJS-Vulcan/pull/36)
PR2: [https://github.com/StateOfJS/StateOfJS-Vulcan/pull/54](https://github.com/StateOfJS/StateOfJS-Vulcan/pull/54)

Thanks in advanced 😊

**Comment by timbergus** [comment]
Thanks a lot, @SachaG.
